<?php
/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

function details_of_the_crime_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function details_of_the_crime_add_meta_box() {
	add_meta_box(
		'details_of_the_crime-details-of-the-crime',
		__( 'Details of the crime', 'details_of_the_crime' ),
		'details_of_the_crime_html',
		'crime_log\\\'',
		'normal',
		'default'
	);
}
add_action( 'add_meta_boxes', 'details_of_the_crime_add_meta_box' );

function details_of_the_crime_html( $post) {
	wp_nonce_field( '_details_of_the_crime_nonce', 'details_of_the_crime_nonce' ); ?>
	
<script>
jQuery(document).ready(function(){
jQuery('#details_of_the_crime_date_reported').datepicker({
	dateFormat: "yy-mm-dd"
});
jQuery('#details_of_the_crime_date_incident_occurred_start').datepicker({
	dateFormat: "yy-mm-dd"
});
	jQuery('#details_of_the_crime_date_incident_occurred_end').datepicker({
	dateFormat: "yy-mm-dd"
});
	jQuery('#details_of_the_crime_secondary_date_incident_occurred_start').datepicker({
	dateFormat: "yy-mm-dd"
});
	jQuery('#details_of_the_crime_secondary_date_incident_occurred_end').datepicker({
	dateFormat: "yy-mm-dd"
});
jQuery('#details_of_the_crime_time_incident_occurred_start').timepicker({
	timeFormat: "hh:mm tt"
});
jQuery('#details_of_the_crime_time_incident_occurred_end').timepicker({
	timeFormat: "hh:mm tt"
});
jQuery('#details_of_the_crime_secondary_time_incident_occurred_start').timepicker({
	timeFormat: "hh:mm tt"
});
jQuery('#details_of_the_crime_secondary_time_incident_occurred_end_').timepicker({
	timeFormat: "hh:mm tt"
});	

});
</script>
	<p>This meta-box for filling out the details of the crime being logged in that occurred  the LCCC Elyria campus.</p>
<h2 style="padding: 0;font-weight: bold;text-decoration: underline;" >Report Date and Time</h2>
	<p>
		<label for="details_of_the_crime_date_reported"><?php _e( 'Date Reported', 'details_of_the_crime' ); ?></label><br>
		<input type="text" name="details_of_the_crime_date_reported" id="details_of_the_crime_date_reported" value="<?php echo details_of_the_crime_get_meta( 'details_of_the_crime_date_reported' ); ?>">
	</p>	<p>
		<label for="details_of_the_crime_time_reported"><?php _e( 'Time Reported', 'details_of_the_crime' ); ?></label><br>
		<input type="text" name="details_of_the_crime_time_reported" id="details_of_the_crime_time_reported" value="<?php echo details_of_the_crime_get_meta( 'details_of_the_crime_time_reported' ); ?>">
	</p>	
<h2 style="padding: 0;font-weight: bold;text-decoration: underline;">Incident Dates and Times</h2>
<p>
		<input type="checkbox" name="details_of_the_crime_unknown_incident_date" id="details_of_the_crime_unknown_incident_date" value="true" <?php echo ( details_of_the_crime_get_meta( 'details_of_the_crime_unknown_incident_date' ) === 'true' ) ? 'checked' : ''; ?>>
		<label for="details_of_the_crime_unknown_incident_date"><?php _e( 'Unknown Incident Date', 'details_of_the_crime' ); ?></label>	</p>	<p>

		<input type="checkbox" name="details_of_the_crime_various_incident_dates" id="details_of_the_crime_various_incident_dates" value="true" <?php echo ( details_of_the_crime_get_meta( 'details_of_the_crime_various_incident_dates' ) === 'true' ) ? 'checked' : ''; ?>>
		<label for="details_of_the_crime_various_incident_dates"><?php _e( 'Various Incident Dates', 'details_of_the_crime' ); ?></label>	</p>	<p>
		<label for="details_of_the_crime_date_incident_occurred_start"><?php _e( 'Date Incident Occurred Start', 'details_of_the_crime' ); ?></label><br>
		<input type="text" name="details_of_the_crime_date_incident_occurred_start" id="details_of_the_crime_date_incident_occurred_start" value="<?php echo details_of_the_crime_get_meta( 'details_of_the_crime_date_incident_occurred_start' ); ?>">
	</p>	<p>
		<label for="details_of_the_crime_date_incident_occurred_end"><?php _e( 'Date Incident Occurred End', 'details_of_the_crime' ); ?></label><br>
		<input type="text" name="details_of_the_crime_date_incident_occurred_end" id="details_of_the_crime_date_incident_occurred_end" value="<?php echo details_of_the_crime_get_meta( 'details_of_the_crime_date_incident_occurred_end' ); ?>">
	</p>	<p>
		<label for="details_of_the_crime_time_incident_occurred_start"><?php _e( 'Time Incident Occurred Start', 'details_of_the_crime' ); ?></label><br>
		<input type="text" name="details_of_the_crime_time_incident_occurred_start" id="details_of_the_crime_time_incident_occurred_start" value="<?php echo details_of_the_crime_get_meta( 'details_of_the_crime_time_incident_occurred_start' ); ?>">
	</p>	<p>
		<label for="details_of_the_crime_time_incident_occurred_end"><?php _e( 'Time Incident Occurred End', 'details_of_the_crime' ); ?></label><br>
		<input type="text" name="details_of_the_crime_time_incident_occurred_end" id="details_of_the_crime_time_incident_occurred_end" value="<?php echo details_of_the_crime_get_meta( 'details_of_the_crime_time_incident_occurred_end' ); ?>">
	</p>	<p>
		<label for="details_of_the_crime_secondary_date_incident_occurred_start"><?php _e( 'Secondary Date Incident Occurred Start', 'details_of_the_crime' ); ?></label><br>
		<input type="text" name="details_of_the_crime_secondary_date_incident_occurred_start" id="details_of_the_crime_secondary_date_incident_occurred_start" value="<?php echo details_of_the_crime_get_meta( 'details_of_the_crime_secondary_date_incident_occurred_start' ); ?>">
	</p>	<p>
		<label for="details_of_the_crime_secondary_date_incident_occurred_end"><?php _e( 'Secondary Date Incident Occurred End', 'details_of_the_crime' ); ?></label><br>
		<input type="text" name="details_of_the_crime_secondary_date_incident_occurred_end" id="details_of_the_crime_secondary_date_incident_occurred_end" value="<?php echo details_of_the_crime_get_meta( 'details_of_the_crime_secondary_date_incident_occurred_end' ); ?>">
	</p>	<p>
		<label for="details_of_the_crime_secondary_time_incident_occurred_start"><?php _e( 'Secondary Time Incident Occurred Start', 'details_of_the_crime' ); ?></label><br>
		<input type="text" name="details_of_the_crime_secondary_time_incident_occurred_start" id="details_of_the_crime_secondary_time_incident_occurred_start" value="<?php echo details_of_the_crime_get_meta( 'details_of_the_crime_secondary_time_incident_occurred_start' ); ?>">
	</p>	<p>
		<label for="details_of_the_crime_secondary_time_incident_occurred_end_"><?php _e( 'Secondary Time Incident Occurred End ', 'details_of_the_crime' ); ?></label><br>
		<input type="text" name="details_of_the_crime_secondary_time_incident_occurred_end_" id="details_of_the_crime_secondary_time_incident_occurred_end_" value="<?php echo details_of_the_crime_get_meta( 'details_of_the_crime_secondary_time_incident_occurred_end_' ); ?>">
	</p>	
<h2 style="padding: 0;font-weight: bold;text-decoration: underline;">Incident Details</h2>
<p>
		<label for="details_of_the_crime_nature_of_offense"><?php _e( 'Nature of Offense', 'details_of_the_crime' ); ?></label><br>
		<input type="text" name="details_of_the_crime_nature_of_offense" id="details_of_the_crime_nature_of_offense" value="<?php echo details_of_the_crime_get_meta( 'details_of_the_crime_nature_of_offense' ); ?>">
	</p>	<p>
		<label for="details_of_the_crime_aleir_report_number"><?php _e( 'ALEIR Report Number', 'details_of_the_crime' ); ?></label><br>
		<input type="text" name="details_of_the_crime_aleir_report_number" id="details_of_the_crime_aleir_report_number" value="<?php echo details_of_the_crime_get_meta( 'details_of_the_crime_aleir_report_number' ); ?>">
	</p>	<p>
		<label for="details_of_the_crime_general_location"><?php _e( 'General Location', 'details_of_the_crime' ); ?></label><br>
		<input type="text" name="details_of_the_crime_general_location" id="details_of_the_crime_general_location" value="<?php echo details_of_the_crime_get_meta( 'details_of_the_crime_general_location' ); ?>">
	</p>	<p>
		<label for="details_of_the_crime_disposition"><?php _e( 'Disposition', 'details_of_the_crime' ); ?></label><br>
		<input type="text" name="details_of_the_crime_disposition" id="details_of_the_crime_disposition" value="<?php echo details_of_the_crime_get_meta( 'details_of_the_crime_disposition' ); ?>">
	</p><?php
}

function details_of_the_crime_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['details_of_the_crime_nonce'] ) || ! wp_verify_nonce( $_POST['details_of_the_crime_nonce'], '_details_of_the_crime_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	if ( isset( $_POST['details_of_the_crime_date_reported'] ) )
		update_post_meta( $post_id, 'details_of_the_crime_date_reported', esc_attr( $_POST['details_of_the_crime_date_reported'] ) );
	if ( isset( $_POST['details_of_the_crime_time_reported'] ) )
		update_post_meta( $post_id, 'details_of_the_crime_time_reported', esc_attr( $_POST['details_of_the_crime_time_reported'] ) );
	if ( isset( $_POST['details_of_the_crime_unknown_incident_date'] ) )
		update_post_meta( $post_id, 'details_of_the_crime_unknown_incident_date', esc_attr( $_POST['details_of_the_crime_unknown_incident_date'] ) );
	else
		update_post_meta( $post_id, 'details_of_the_crime_unknown_incident_date', null );
	if ( isset( $_POST['details_of_the_crime_various_incident_dates'] ) )
		update_post_meta( $post_id, 'details_of_the_crime_various_incident_dates', esc_attr( $_POST['details_of_the_crime_various_incident_dates'] ) );
	else
		update_post_meta( $post_id, 'details_of_the_crime_various_incident_dates', null );
	if ( isset( $_POST['details_of_the_crime_date_incident_occurred_start'] ) )
		update_post_meta( $post_id, 'details_of_the_crime_date_incident_occurred_start', esc_attr( $_POST['details_of_the_crime_date_incident_occurred_start'] ) );
	if ( isset( $_POST['details_of_the_crime_date_incident_occurred_end'] ) )
		update_post_meta( $post_id, 'details_of_the_crime_date_incident_occurred_end', esc_attr( $_POST['details_of_the_crime_date_incident_occurred_end'] ) );
	if ( isset( $_POST['details_of_the_crime_time_incident_occurred_start'] ) )
		update_post_meta( $post_id, 'details_of_the_crime_time_incident_occurred_start', esc_attr( $_POST['details_of_the_crime_time_incident_occurred_start'] ) );
	if ( isset( $_POST['details_of_the_crime_time_incident_occurred_end'] ) )
		update_post_meta( $post_id, 'details_of_the_crime_time_incident_occurred_end', esc_attr( $_POST['details_of_the_crime_time_incident_occurred_end'] ) );
	if ( isset( $_POST['details_of_the_crime_secondary_date_incident_occurred_start'] ) )
		update_post_meta( $post_id, 'details_of_the_crime_secondary_date_incident_occurred_start', esc_attr( $_POST['details_of_the_crime_secondary_date_incident_occurred_start'] ) );
	if ( isset( $_POST['details_of_the_crime_secondary_date_incident_occurred_end'] ) )
		update_post_meta( $post_id, 'details_of_the_crime_secondary_date_incident_occurred_end', esc_attr( $_POST['details_of_the_crime_secondary_date_incident_occurred_end'] ) );
	if ( isset( $_POST['details_of_the_crime_secondary_time_incident_occurred_start'] ) )
		update_post_meta( $post_id, 'details_of_the_crime_secondary_time_incident_occurred_start', esc_attr( $_POST['details_of_the_crime_secondary_time_incident_occurred_start'] ) );
	if ( isset( $_POST['details_of_the_crime_secondary_time_incident_occurred_end_'] ) )
		update_post_meta( $post_id, 'details_of_the_crime_secondary_time_incident_occurred_end_', esc_attr( $_POST['details_of_the_crime_secondary_time_incident_occurred_end_'] ) );
	if ( isset( $_POST['details_of_the_crime_nature_of_offense'] ) )
		update_post_meta( $post_id, 'details_of_the_crime_nature_of_offense', esc_attr( $_POST['details_of_the_crime_nature_of_offense'] ) );
	if ( isset( $_POST['details_of_the_crime_aleir_report_number'] ) )
		update_post_meta( $post_id, 'details_of_the_crime_aleir_report_number', esc_attr( $_POST['details_of_the_crime_aleir_report_number'] ) );
	if ( isset( $_POST['details_of_the_crime_general_location'] ) )
		update_post_meta( $post_id, 'details_of_the_crime_general_location', esc_attr( $_POST['details_of_the_crime_general_location'] ) );
	if ( isset( $_POST['details_of_the_crime_disposition'] ) )
		update_post_meta( $post_id, 'details_of_the_crime_disposition', esc_attr( $_POST['details_of_the_crime_disposition'] ) );
}
add_action( 'save_post', 'details_of_the_crime_save' );

/*
	Usage: details_of_the_crime_get_meta( 'details_of_the_crime_date_reported' )
	Usage: details_of_the_crime_get_meta( 'details_of_the_crime_time_reported' )
	Usage: details_of_the_crime_get_meta( 'details_of_the_crime_unknown_incident_date' )
	Usage: details_of_the_crime_get_meta( 'details_of_the_crime_various_incident_dates' )
	Usage: details_of_the_crime_get_meta( 'details_of_the_crime_date_incident_occurred_start' )
	Usage: details_of_the_crime_get_meta( 'details_of_the_crime_date_incident_occurred_end' )
	Usage: details_of_the_crime_get_meta( 'details_of_the_crime_time_incident_occurred_start' )
	Usage: details_of_the_crime_get_meta( 'details_of_the_crime_time_incident_occurred_end' )
	Usage: details_of_the_crime_get_meta( 'details_of_the_crime_secondary_date_incident_occurred_start' )
	Usage: details_of_the_crime_get_meta( 'details_of_the_crime_secondary_date_incident_occurred_end' )
	Usage: details_of_the_crime_get_meta( 'details_of_the_crime_secondary_time_incident_occurred_start' )
	Usage: details_of_the_crime_get_meta( 'details_of_the_crime_secondary_time_incident_occurred_end_' )
	Usage: details_of_the_crime_get_meta( 'details_of_the_crime_nature_of_offense' )
	Usage: details_of_the_crime_get_meta( 'details_of_the_crime_aleir_report_number' )
	Usage: details_of_the_crime_get_meta( 'details_of_the_crime_general_location' )
	Usage: details_of_the_crime_get_meta( 'details_of_the_crime_disposition' )
*/

?>